name: Run tests
on : 
  pull_request
jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes


    permissions:
      issues: write
      pull-requests: write
    steps: 
     - name : Checkout code
       uses: actions/checkout@v4.2.2

     - name : setup php and composer
       uses: shivammathur/setup-php@2.32.0
       with:
        php-version: '8.4'
        tools: composer:v2
        extensions: mbstring, pdo, pdo_mysql
        
     - name : install dependencies
       run: composer install -q --no-interaction

     - name : prep application
       run : |
        cp .env.example .env
        php artisan key:generate

     - name : run tests
       run : php artisan test  --compact


